### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by nedz14** [areebbeigh/anime-scraper#1]
first thanks for this tool, after trying it here what i get:
C:\Users\user\Videos\anime-scraper-3.0.0>python pdl.py www3.animeland.tv/dub/clannad -s 10 -e 20
Traceback (most recent call last):
  File "pdl.py", line 9, in <module>
    from src import scraper
  File "C:\Users\user\Videos\anime-scraper-3.0.0\src\scraper.py", line 144
    print(episode + ":", download_url, end="\n\n")
                                          ^
SyntaxError: invalid syntax

C:\Users\user\Videos\anime-scraper-3.0.0>

**Comment by areebbeigh** [comment]
Hello nedz,

I forgot to mention that the tool isn't yet functional. Should've named the branch dev branch. pdl.py will soon be replaced too. Still working on it.

Support for all websites is terminated in favor of kickassanime.ru in the new version. New websites may be added as well. 

Also, you're probably using Python 2. anime-scraper is written in Python 3.

**Comment by areebbeigh** [comment]
Once v3.0.0 is usable it'll replace the master branch.

**Comment by nedz14** [comment]
Noted, thank you.

**Comment by areebbeigh** [comment]
You can use anime-scraper v3 now.
