### ISSUE TITLE
 warnings.warn(warning, RequestsDependencyWarning)

### ISSUE THREAD

**Issue by streamaly** [areebbeigh/anime-scraper#4]
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "scrape.py", line 17, in <module>
    from src.websites.kickassanime import Scraper as KickassAnimeScraper
  File "/root/anime-scraper/src/websites/kickassanime.py", line 12, in <module>
    from src.utils import printing
  File "/root/anime-scraper/src/utils/printing.py", line 7
    print(tag, episode_name, stream_url, end="\n\n")
                                            ^
SyntaxError: invalid syntax

**Comment by areebbeigh** [comment]
anime-scraper is written in Python3.
